name: CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    env:
      PIPENV_NOSPIN: 'true'
      WORKON_HOME: ~/.pipenv/virtualenvs
      PIPENV_CACHE_DIR: ~/.pipenv/pipcache
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Cache Pipenv virtualenv
        uses: actions/cache@v2
        id: pipenv-cache
        with:
          path: ~/.pipenv
          key: ${{ runner.os }}-pipenv-3.10-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-3.10-

      - name: Install Dependencies
        run: pipenv install --dev --deploy
        if: steps.pipenv-cache.outputs.cache-hit != 'true'

      - name: Isort
        run: |
          pipenv run isort --check-only .
      - name: Black
        run: |
          pipenv run black --check .
      - name: Flake8
        run: |
          pipenv run flake8 .
      - name: Mypy
        run: |
          pipenv run mypy .

      - name: Build package 🐍
        run: pipenv run python -m build --sdist --wheel --outdir dist/

      - id: upload
        name: Publish distribution 📦 to fury.io
        # Only publishes tags
        if: startsWith(github.ref, 'refs/tags')
        run: |
          ls -l dist
          curl -F package=@$(ls dist/django-monthfield-*-py3-none-any.whl) https://${{ secrets.FURY_IO_UPLOAD_TOKEN }}@push.fury.io/spatialquotient/

